version: '3.8'

services:
  weather-app:
    build:
      context: . # Il contesto di build è la directory corrente
      dockerfile: Dockerfile # Specifica il Dockerfile da usare
    ports:
      - "8080:8080" # Mappa la porta 8080 del container alla porta 8080 dell'host
    container_name: weather-app-container # Nome del container
    restart: unless-stopped # Riavvia il container a meno che non venga fermato esplicitamente
